config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'users', to: 'users/registrations#new'
  end

  root 'items#index'
  
  resources :categories, only: [:index,]

  resources :users, only: [:show] do
    member do
      get 'sales_items'
      get 'sold_items'
      get 'logout'
    end
    collection do
      get 'commented_items'
    end
  end
  
  resources :items do
    resources :comments, only: [:create, :destroy]
    member do
      get 'buy'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      get 'search'
      get 'post_done'
      get 'delete_done'
      get 'detail_search'
      get 'update_done'
    end
    resources :purchase, only: [:index] do
      collection do
        get 'done', to: 'purchase#done'
        post 'pay', to: 'purchase#pay'
      end
    end
  end


  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true
  validates :password, length: { minimum: 7 }
  validates :last_name, :first_name,  presence: true,
                                      format: {
                                        with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/,
                                        message: "は全角で入力して下さい"
                                      }
  validates :last_name_kana, :first_name_kana,  presence: true,
                                                format: {
                                                  with: /\A[ァ-ヶー－]+\z/,
                                                  message: "は全角カタカナで入力して下さい"
                                                }
  validates :birth_year, :birth_month, :birth_day, presence: true

  has_one :card, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :bought_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :sales_items, -> { where buyer_id: nil }, foreign_key: "seller_id", class_name: "Item"
  has_many :sold_items, -> { where.not buyer_id: nil }, foreign_key: "seller_id", class_name: "Item"
  has_many :comments,  dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def address_params
    params.require(:address).permit(:send_last_name, :send_first_name, :send_last_name_kana, :send_first_name_kana, :postal_code, :prefecture_id, :city, :address, :build_name, :phone_number)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users = User.select("nickname")
  end

  def sales_items
    @sales_items = User.find(params[:id]).sales_items.includes(:images)
  end

  def sold_items
    @sold_items = User.find(params[:id]).sold_items.includes(:images)
  end
  
  def logout
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side_bar.html.haml
.side-bar
  %ul.my-page
    %li
      = link_to "マイページ", user_path(current_user.id)
    %li
      = link_to "出品する", new_item_path
    %li
      = link_to "出品した商品", sales_items_user_path(current_user.id)
    %li
      = link_to "売却済みの商品", sold_items_user_path(current_user.id)
    %li
      = link_to "購入した商品"
    %li
      = link_to "プロフィール"
    %li
      = link_to "発送元・お届け先住所変更"
    %li
      = link_to "クレジットカード登録・変更", new_card_path(current_user.id)
    %li
      = link_to "メール・パスワード"
    %li
      = link_to "本人情報"
    %li
      = link_to "ログアウト", logout_user_path(current_user.id)

app/views/users/logout.html.haml
- breadcrumb :logout

.wrapper
  = render partial: 'items/header'

%main
  .logout-page
    .logout-page__content
      .logout-page__form
        .logout-page__btn
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn-default"

= render partial: 'items/footer'

app/views/users/sales_items.html.haml
- breadcrumb :sales_items

= render partial: 'items/header'

.my-page-main
  = render partial: "side_bar"
  .User-my-page
    %h1 出品中の商品
    .User-my-page__main
      - @sales_items.each do |sales_item|
        .My-page-content
          = link_to '', edit_item_path(sales_item.id)
          .My-page-content__image
            = image_tag(sales_item.images.first.src.url, alt: '商品画像', width: '120px', height: '120px')
          .My-page-content__contents
            %h1= sales_item.name
            .My-page-content__contents--price
              %span 税込価格
              %p= sales_item.price
            .My-page-content__contents--explain
              %span 商品説明
              %p= sales_item.explain

= render partial: 'items/footer'

app/views/users/show.html.haml
- breadcrumb :mypage

= render partial: 'items/header'

.my-page-main
  = render partial: "side_bar"

  .main-content
    .main-content__photo
      = link_to image_tag('material/icon/member_photo_noimage_thumb.png' , alt: 'プロフィール画像', :size => '200x200')
    .main-content__name
      = current_user.nickname
    .main-content__text

= render partial: 'items/sell_btn'
= render partial: 'items/footer_invitation'
= render partial: 'items/footer'

app/views/users/sold_items.html.haml
- breadcrumb :sold_items

= render partial: 'items/header'

.my-page-main
  = render partial: "side_bar"
  .User-my-page
    %h1 売却済みの商品
    .User-my-page__main
      - @sold_items.each do |sold_item|
        .My-page-content
          = link_to '', item_path(sold_item.id)
          .My-page-content__image
            = image_tag(sold_item.images.first.src.url, alt: '商品画像', width: '120px', height: '120px')
          .My-page-content__contents
            %h1= sold_item.name
            .My-page-content__contents--price
              %span 税込価格
              %p= sold_item.price
            .My-page-content__contents--explain
              %span 商品説明
              %p= sold_item.explain

= render partial: 'items/footer' 