config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'users', to: 'users/registrations#new'
  end

  root 'items#index'
  
  resources :categories, only: [:index,]

  resources :users, only: [:show] do
    member do
      get 'sales_items'
      get 'sold_items'
      get 'logout'
    end
    collection do
      get 'commented_items'
    end
  end
  
  resources :items do
    resources :comments, only: [:create, :destroy]
    member do
      get 'buy'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      get 'search'
      get 'post_done'
      get 'delete_done'
      get 'detail_search'
      get 'update_done'
    end
    resources :purchase, only: [:index] do
      collection do
        get 'done', to: 'purchase#done'
        post 'pay', to: 'purchase#pay'
      end
    end
  end


  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id", optional: true
  belongs_to :category
  has_many :comments,  dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  validates_associated :images
  validates :images, presence: { message: "は一枚以上必須です" }

  validates :name, presence: true
  validates :price, presence: true
  validates :explain, presence: true
  validates :item_status_id, presence: true
  validates :prefecture_id, presence: true
  validates :postage_id, presence: true
  validates :shipping_date_id, presence: true
  validates :seller_id, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :item_status
  belongs_to_active_hash :postage

  def self.search(search)
    if search != ""
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :permit_only_seller, only: [:edit, :update, :destroy]
  before_action :set_category, only: [:new, :edit, :create, :update, :destroy]

  def index
    @items = Item.includes(:images).order('created_at DESC').limit(5)
  end

  def new
    @item = Item.new
    @item.images.build
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @parents = Category.all
    @comment = Comment.new
    @comments = @item.comments.includes(:seller)
  end


  def destroy
    if @item.destroy
      redirect_to delete_done_items_path
    else
      flash[:alert] = '削除できませんでした'
      render :show
    end
  end

  def search
    @keyword = params[:keyword]
    @items = Item.search(params[:keyword]).includes(:images).order('created_at DESC')
  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  private

  def permit_only_seller
    redirect_to root_path, alert: "出品者のみが許可されるページです" unless set_item.seller_id == current_user.id
  end

  def item_params
    params.require(:item).permit(:name, :price, :explain, :size, :prefecture_id, :brand, :shipping_date_id, :item_status_id, :postage_id, :category_id, images_attributes: [:src, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_category  
    @category_parent_array = Category.where(ancestry: nil)
  end

  def buy
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error_message.html.haml
- if @item.errors.any?
  .Error-message
    %p
      = @item.errors.full_messages_for(column).first

app/views/items/_footer.html.haml
.footer
  .footer-content
    %ul.left-content
      %h2 FURIMAについて
      %li= link_to "会社概要(運営会社)"
      %li= link_to "プライバシーポリシー"
      %li= link_to "FURIMA利用規約"
      %li= link_to "ポイントに関する特約"
    %ul.center-content
      %h2 FURIMAを見る
      %li= link_to "カテゴリー一覧",categories_path
      %li= link_to "ブランド一覧"
    %ul.right-content
      %h2 ヘルプ＆ガイド
      %li= link_to "FURIMAガイド"
      %li= link_to "FURIMAロゴ利用ガイドライン"
      %li= link_to "お知らせ"
  .footer-logo
    = image_tag 'material/logo/logo-white.png' , alt: '使用例の画像', :size => '180x50'
  .footer-copyright
    ©︎FURIMA

app/views/items/_footer_invitation.html.haml
.Footer-invitation
  .Footer-invitation__content
    %h4
      だれでもかんたん、人生を変えるフリマアプリ
    %h2
      今すぐ無料ダウンロード！
  .Download-link.position-center
    = link_to image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', alt: 'Download on the App Store', width: '175px', class: 'Download-link__apple'), root_path
    = link_to image_tag('badge/google-play-badge.png', alt: 'GET IT ON Google Play', width: '200px', class: 'Download-link__google'), root_path

app/views/items/_header.html.haml
.header
  .header-top
    .header-top__logo
      = link_to image_tag('material/logo/logo.png' , alt: 'ロゴ', size:'140x40'), root_path
    
    = form_with url: search_items_path, local: true, method: :get, class: "header-top__search-bar" do |f|
      = f.text_field :keyword, placeholder: "キーワードから探す", class: "item-search"
      %label.search-btn
        .search-icon
          = image_tag 'material/icon/icon-search 1.png', alt: '検索ボタン', class: "search-icon_btn"
        = f.submit "検索"

  .header-bottom
    %ul.header-bottom__left
      %li 
        =link_to "カテゴリーから探す"
      %li 
        =link_to "ブランドから探す"
    .header-bottom__right
      - if user_signed_in?
        = link_to "マイページ", user_path(current_user.id)
      - else
        = link_to "ログイン", new_user_session_path, class: "post"
        = link_to "新規登録", new_user_registration_path, class: "post"

= breadcrumbs separator: " &#9656; ", class: "breadcrumbs"

app/views/items/_notifications.html.haml
- if flash[:alert]
  .Notifications
    - flash.each do |key, value|
      = content_tag(:div, value, class: key)

app/views/items/_sell_btn.html.haml
.Sell-btn
  %p 出品する
  = image_tag('material/icon/icon_camera.png', alt: '出品ページへのリンクボタン', width: '54', height: '54')
  = link_to '', new_item_path

app/views/items/delete_done.html.haml
.wrapper
  = render partial: 'items/header'

%main
  .sakujyo-page
    .sakujyo-page__content
      .sakujyo-page__form
        削除しました
        .sakujyo-page__btn
          = link_to "トップページに戻る", root_path, class: "btn-default"

= render partial: 'items/footer'

app/views/items/destroy.html.haml
.wrapper
  = render partial: 'items/header'

%main
  .sakujyo-page
    .sakujyo-page__content
      .sakujyo-page__form
        .sakujyo-page__btn
          = link_to "削除が完了しました。", destroy_user_session_path, method: :delete, class: "btn-default"

= render partial: 'items/footer'

app/views/items/edit.html.haml
.exhibit__page
  = form_with model: @item, local: true do |f|
    .exhibit__page__main
      .exhibit__page__main__contents
        %h3.exhibit__page__main__contents__message
          商品の情報を入力
        .form-content
          .img-form
            %h3.img__upload__text
              出品画像
              %span.form--caution 
                必須
            %p.img__upload__comment 最大5枚までアップロードできます（jpg/jpeg/png画像、上限100KBまで）

            .dropbox
              
            #image-box
              #previews
                - if @item.persisted?
                  - @item.images.each_with_index do |image, i|
                    .preview
                      %label{for: "item_images_attributes_#{i}_src"}
                        = image_tag image.src.url, data: {index: i}, width: "120px", height: "120px", id: "reselect-image", class: "image-#{i}"
                      %div{class: "data-dele-btn", id: "delete-num-#{i}"} 削除
                %label{for: "item_images_attributes_0_src", class: "dropbox__img"}
                  = icon('fas', 'camera')
                  -# %p ドラッグアンドドロップ<br>または
                  %p クリックしてファイルをアップロード

              = f.fields_for :images do |image|
                %div{ data: {index: image.index}, class: "reselection" }
                  = image.file_field :src, class: "js-file"
                  - if @item.persisted?
                    = image.check_box :_destroy, data: { index: image.index }, class: "hidden-destroy"
              - if @item.persisted?
                %div{ data: {index: @item.images.count}, class: "js-file_group" }
                  = file_field_tag "item_images_attributes_#{@item.images.count}_src", name: "item[images_attributes][#{@item.images.count}][src]", class: "js-file"
                
              = render partial: 'error_message', locals: { column: :images }

        .sell--content
          .sell--content__name
            %h3.sell--content__name__name
              商品名
              %span.form--caution 
                必須
            %div
              = f.text_field :name,  class: "Form__textContent", placeholder:"商品名（必須40文字まで）" 
              = render partial: 'error_message', locals: { column: :name }
          .sell--content__description
            %h3.sell--content__description__description
              商品の説明
              %span.form--caution 
                必須
              = f.text_area :explain, class: "Form__textareaContent", placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
              = render partial: 'error_message', locals: { column: :explain }
        .product-details
          %h3.product-details__name 商品の詳細
          .product-details__form
            .product-details__form__category
              %h3.product-details__form__category__name
                カテゴリー
                %span.form--caution 必須
                - if @item.category != nil
                  .select--wrap
                    = f.collection_select :category_id, @category_parent_array, :id, :name, { selected: @item.category.root.id }, class:"select--wrap__box1"
                  .select--wrap#children_wrapper
                    = f.collection_select :category_id, @item.category.parent.parent.children, :id, :name, { selected: @item.category.parent.id }, class:"select--wrap__box1", id:"child__category"
                  .select--wrap#grandchildren_wrapper
                    = f.collection_select :category_id, @item.category.parent.children, :id, :name, { selected:  @item.category.id }, class:"select--wrap__box1"
                - else
                  .select--wrap
                    = f.collection_select :category_id, @category_parent_array, :id, :name, { include_blank: "選択してください"}, class:"select--wrap__box1"
                  
                = render partial: 'error_message', locals: { column: :category }
  
            .product-details__form__brand
              %h3.product-details__form__brand__name
                ブランド
                %span.form--caution 任意
                .select--wrap
                  = f.text_field :brand, class: "select--wrap__box", placeholder:"例）シャネル" 
                  = render partial: 'error_message', locals: { column: :brand }
            .product-details__form__status
              %h3.product-details__form__status__name
                商品の状態
                %span.form--caution 必須
                .select--wrap
                  = f.collection_select :item_status_id, ItemStatus.all, :id, :choice, {prompt: "選択してください"}, {class: "select--wrap__box"}
                  = render partial: 'error_message', locals: { column: :item_status_id }
  
        .delivery-form
          %h3.delivery-form__about__delivery 配送について
          = link_to '?', new_item_path, class: 'form--question'
          .delivery-form__box
            .delivery-form__box__top
              %h3.delivery-form__box__top__name
                配送料の負担
                %span.form--caution 必須
              .select--wrap
                = f.collection_select :postage_id, Postage.all, :id, :choice, {prompt: "選択してください"}, {class: "select--wrap__box"}
                = render partial: 'error_message', locals: { column: :postage_id }

            .delivery-form__box__middle
              %h3.delivery-form__box__top__name
                発送元の地域
                %span.form--caution 必須
              .select--wrap
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: "select--wrap__box"}
                = render partial: 'error_message', locals: { column: :prefecture_id }

            .delivery-form__box__bottom
              %h3.delivery-form__box__top__name
                発送までの日数
                %span.form--caution 必須
              .select--wrap
                = f.collection_select :shipping_date_id, ShippingDate.all, :id, :choice, {prompt: "選択してください"}, {class: "select--wrap__box"}
                = render partial: 'error_message', locals: { column: :shipping_date_id }

        .product-price
          %h3.product-price__name 価格(300〜9,999,999)
          = link_to '?', new_item_path, class: 'form--question'
          .product-price__form
            .product-price__form__left
              %h3.product-price__form__name
                販売価格
              %span.form--caution 必須
            .select--wrap
              .price-field
                %span ¥
                = f.number_field :price, in: 300..9999999, step:1, class: "select--wrap__box"
            
        .submit-button
          .actions
            = f.submit "更新する", class: "btn--lightblue"
          = link_to 'もどる', new_item_path, class: 'btn--bule'
          .subimit-button__text
            = link_to '禁止されている出品', new_item_path, class: 'submit__text'
            、
            = link_to '行為', new_item_path, class: 'submit__text'
            を必ずご確認ください。
            %p.sell--content5__p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to '偽ブランドの販売', new_item_path, class: 'submit__text'
              は犯罪であり処罰される可能性があります。
            %p.sell--content5__p
              また、出品をもちまして
              = link_to '加盟店規約', new_item_path, class: 'submit__text'
              に同意したことになります。

.exhibit-page__footer
  .exhibit-page__footer__content
    .exhibit-page__footer__content__main
      %ul.exhibit-page__footer__lists
        %li.exhibit-page__footer__list
          プライバシーポリシー
        %li.exhibit-page__footer__list
          FURIMA利用規約
        %li.exhibit-page__footer__list
          特定商取引に関する表記
        %p.exhibit-page__footer__copyright
          2020 FURIMA

app/views/items/index.html.haml
= render partial: 'notifications'
= render partial: 'header'

.Top-screen
  .Top-screen__contents
    %h1
      人生を変えるフリマアプリ
    %p
      FURIMAはだれでもかんたんに出品・購入できる
      %br フリマアプリです

    .Download-link
      = link_to image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', alt: 'Download on the App Store', width: '175px', class: 'Download-link__apple'), root_path
      = link_to image_tag('badge/google-play-badge.png', alt: 'GET IT ON Google Play', width: '200px', class: 'Download-link__google'), root_path

.Reasons
  %h1
    FURIMAが選ばれる3つの理由
  .Reasons__contents
    .Reason-list
      .Reason-list__num
        1
      = image_tag 'material/pict/pict-reason-01.jpg', alt: '使用例の画像'
      %h2
        %span
          3分
        ですぐに出品
      %p
        スマホで入力するだけで簡単に出品できる！
    .Reason-list
      .Reason-list__num
        2
      = image_tag 'material/pict/pict-reason-02.jpg', alt: '使用例の画像'
      %h2
        %span
          シンプル 
        で使いやすい
      %p
        めんどくさい入力は必要なく、検索も購入もスムーズ！
    .Reason-list
      .Reason-list__num
        3
      = image_tag 'material/pict/pict-reason-03.jpg', alt: '使用例の画像'
      %h2
        手数料 
        %span
          業界最安
      %p.space
        最大3%でお得に出品&購入！

.Download-invitation
  .Download-invitation__content
    %h2
      会員数日本一位
    %p FURIMAは、フリマアプリで最も人気。
    %p 出品・購入回数も業界最多です！
    %p ほしかったあの商品に出会えるかもしれません。
  .Download-link
    = link_to image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', alt: 'Download on the App Store', width: '175px', class: 'Download-link__apple'), root_path
    = link_to image_tag('badge/google-play-badge.png', alt: 'GET IT ON Google Play', width: '200px', class: 'Download-link__google'), root_path

.Features
  %h1
    FURIMAの特徴
  .Features__contents
    .Feature-list
      = image_tag 'material/icon/icon-01.png', alt: 'アプリケーションの特徴を表す画像'
      %h1
        簡単に売り買いできる
      %p
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

    .Feature-list
      = image_tag 'material/icon/icon-03.png', alt: 'アプリケーションの特徴を表す画像'
      %h1
        売上金は即日振込みに対応
      %p
        午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!

    .Feature-list
      = image_tag 'material/icon/icon-04.png', alt: 'アプリケーションの特徴を表す画像'
      %h1
        様々な支払いに対応
      %p
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

// 始めは商品一覧がきます
.Pickup
  %h1
    ピックアップカテゴリー
  = link_to '新規投稿商品', root_path, class: 'Pickup__link'
  .Pickup__items
    - @items.each do |item|
      .Item-contents
        = link_to item_path(id: item[:id]) do
          .Item-link
            = image_tag(item.images.first.src.url)
            .Item-link__text
              %p
                = item.name
              %p
                = "#{item.price}円"
              %p (税込)
          -if item.buyer_id.present?
            .Pickup__items__sold
              .Pickup__items__sold__inner
                SOLD

// 始めは商品一覧がきます
.Pickup.bottom
  %h1
    ピックアップブランド
  = link_to 'アーカイブ', root_path, class: 'Pickup__link'
  .Pickup__items
    - @items.each do |item|
      .Item-contents
        = link_to item_path(id: item[:id]) do
          .Item-link
            = image_tag(item.images.first.src.url)
            .Item-link__text
              %p
                = item.name
              %p
                = "#{item.price}円"
              %p (税込)
          -if item.buyer_id.present?
            .Pickup__items__sold
              .Pickup__items__sold__inner
                SOLD

= render partial: 'sell_btn'
= render partial: 'footer_invitation'
= render partial: 'footer.html.haml'

app/views/items/search.html.haml
- breadcrumb :search

= render partial: 'header'

.Search
  .Search__side
    %h2 詳細検索
    %h3 キーワードを追加する
    %h3 カテゴリーを選択する
    %h3 価格
    %h3 商品の状態
    %h3 配送料の負担
    %h3 販売状況
    .Search__side--btns
      .clear クリア
      .complete 完了

  .Search__main
    .Search__main--title
      - if @keyword == ""
        %h2.bold すべての商品
      %h2.bold= @keyword
      %span の検索結果
      .Search__main--title__count
        = @items.length
        %span 件表示
    .Search__main--contents
      - if @items.length == 0
        %p お探しの商品は見つかりませんでした
      - @items.each do |item|
        .Searched-item
          = link_to '', item_path(item.id)
          = image_tag(item.images.first.src.url)
          .Searched-item__price
            %span ¥
            %span= item.price
          .Searched-item__name
            = item.name


= render partial: 'sell_btn'
= render partial: 'footer_invitation'
= render partial: 'footer'

app/views/items/show.html.haml
= render partial: 'items/notifications'
= render partial: 'header'

.showMain
  .itembox
    %h1.itembox__name
      = @item.name
    .itembox__body
      %ul.image__main
        %li.image__main__list
          = image_tag @item.images.first.src.url, size: "560x346"
          %ul.image__sub
            - @item.images.each do |img|
              %li.image__sub__list
                = image_tag(img.src.url, class: "sub__photo", size: "90x90", id: "thumbnail")
    .itembox__price
      %span
        ¥
        =@item.price
      .itembox__price__detail
        %span
          (税込)
        %span
          送料込み
    .itemDetail
      =@item.explain
    .itemTable
      %table
        %tbody
          %tr
            %th 出品者
            %td 
              =@item.seller.nickname
          %tr
            %th カテゴリー
            - @parents.each do |parent|
              - if @item.category_id == parent.id
                %td
                  = link_to "#" do
                    = parent.parent.parent.name #親カテゴリー
                    %br
                  = link_to "#" do
                    = parent.parent.name #子カテゴリー
                    %br
                  = link_to "#" do
                    = parent.name #孫カテゴリー
          %tr
            %th
              ブランド
            %td
              = @item.brand
          %tr
            %th
              商品のサイズ
            %td
          %tr
            %th
              商品の状態
            %td
              = @item.item_status.choice
          %tr
            %th
              配送料の負担
            %td
              = @item.postage.choice
          %tr
            %th
              発送元の地域
            %td
              = @item.prefecture.name
          %tr
            %th
              発送日の目安
            %td
              = @item.shipping_date.choice

    .optionalBtn
      .optionalBtn__likeBtn
        = icon('fa', 'star')
        お気に入り１
      .optionalBtn__hata
        = icon('fa', 'flag')
        = link_to '不適切な商品の通報', root_path, class: 'optionalBtn__hata__link'
  .item-buy__btn__box
    - if user_signed_in? && current_user.id == @item.seller_id
      = link_to '商品の編集', "/items/#{@item.id}/edit", method: :get, class: "edit_btn"
      = link_to 'この商品を削除する', item_path(@item.id), method: :delete, class: "delete_btn"
    - elsif user_signed_in?
      = link_to "購入画面に進む", item_purchase_index_path(@item.id), class: "pay_btn"
    - else user_signed_in?
      = link_to "新規会員登録/ログインが必要です", new_user_session_path, class: "login_btn"
  .commentBox
    .title
      コメント一覧
    .commentBox__comments
      - if @comments
        - @comments.each do |comment|
          -if comment.seller_id == @item.seller_id
            .commentBox__comment
              .profile
                .profile__name
                  = comment.seller.nickname
                .profile__right
                  .image
                    = icon('fas', 'user-circle')
                  .seller_or_buyer
                    出品者
              .comment
                .comment__text
                  = comment.comment
                .comment__bottom
                  .comment__date
                    = icon('far', 'clock')
                    = comment.days_passed
                  .comment__trash
                    = link_to item_comment_path(comment.item.id, comment.id), "item_id": :@item, method: :delete do
                      = icon('fa', 'trash')
          - else
            .commentBox__comment__other
              .profile__right
                .image
                  = icon('far', 'user-circle')
                .seller_or_buyer
                  お客様
              .profile__name
                = comment.seller.nickname
              .comment
                .comment__text
                  = comment.comment
                .comment__bottom
                  .comment__icon
                    .flag
                      = icon('far', 'flag')
                    .trash
                      = link_to item_comment_path(comment.item.id, comment.id), "item_id": :@item, method: :delete do
                        = icon('fa', 'trash')
                  .date
                    = icon('far', 'clock')
                    = comment.days_passed
    -if user_signed_in?
      = form_with model: [@item, @comment], local: true, class: "new_comment", id: "comment_form" do |f|
        %p.commentBox__noticeMsg
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
        = f.text_area :comment, required: "required", class: "text_area"
        = f.submit "コメントする", class: "commentBtn"
    - else
      %p.not_comment
        ※コメントの投稿には新規会員登録/ログインが必要です※
  .links
    .links__before
      = icon('fa', 'angle-left', class: "links__before__icon")
      = link_to '前の商品', root_path, class: 'links__before__Btn'
    .links__after
      = link_to '後ろの商品', root_path, class: 'links__after__Btn'        
      = icon('fa', 'angle-right', class: "links__after__icon")

  .relatedItems
    = link_to 'レディースをもっと見る', root_path, class: 'relatedItems__Btn'
    .productLists
      .productList
        = link_to '', root_path
        = image_tag('https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png', alt: '商品の画像', class: 'productList__img')
        .productList__body
          %p.productList__body__name product1
          .productList__body__details
            %ul.productList__body__details__kakaku
              %li.productList__body__details__yen 10000円
              %li.productList__body__details__kakaku__icon
                = icon('fa', 'star')
                1
            %p.productList__body__details__zei (税込)

= render partial: 'sell_btn'
= render partial: 'footer_invitation'
= render partial: 'footer.html.haml'